# Generated by Django 4.0.6 on 2022-08-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='surname',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterModelTable(
            name='studentmodel',
            table='myform_studentmodel',
        ),
    ]
